version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-haskell-hello-world"
s3_bucket = "bellroy-sam-cli-deployments"
s3_prefix = "sam-haskell-hello-world"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"

